console.log("data conected.");
const jobs = [
  {
    companyName: "Google",
    position: "Frontend Developer",
    location: "Remote",
    type: "Full-time",
    salary: "$120,000 - $150,000",
    status: "all",
  },
  {
    companyName: "Facebook",
    position: "Backend Developer",
    location: "New York, NY",
    type: "Full-time",
    salary: "$110,000 - $140,000",
    status: "Interview",
  },
  {
    companyName: "Amazon",
    position: "Fullstack Developer",
    location: "Seattle, WA",
    type: "Full-time",
    salary: "$100,000 - $130,000",
    status: "Rejected",
  },
  {
    companyName: "Microsoft",
    position: "Data Analyst",
    location: "Redmond, WA",
    type: "Full-time",
    salary: "$90,000 - $120,000",
    status: "all",
  },
  {
    companyName: "Netflix",
    position: "UI/UX Designer",
    location: "Los Angeles, CA",
    type: "Part-time",
    salary: "$80,000 - $120,000",
    status: "Interview",
  },
  {
    companyName: "Tesla",
    position: "Mechanical Engineer",
    location: "Palo Alto, CA",
    type: "Full-time",
    salary: "$100,000 - $110,000",
    status: "Rejected",
  },
  {
    companyName: "Apple",
    position: "iOS Developer",
    location: "Cupertino, CA",
    type: "Full-time",
    salary: "$130,000 - $145,000",
    status: "all",
  },
  {
    companyName: "Spotify",
    position: "Product Manager",
    location: "Stockholm, Sweden",
    type: "Full-time",
    salary: "$110,000 - $125,000",
    status: "Interview",
  },
];
